config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/createquestion", to: "questions#new"
    post "/createquestion", to: "questions#create"
    get "/createcategory", to: "categories#new"
    post "/createcategory", to: "categories#create"
    get "/createlesson", to: "lessons#new"
    post "/createlesson", to: "lessons#create"
    get "/testlesson", to: "results#new"
    post "/testlesson", to: "results#create"
    
    resources :users, only: %i(show edit update)
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :questions
    resources :categories
    resources :lessons
    resources :results

    namespace :admin do
      root "users#index"
      delete "/users/:id", to: "users#destroy",
        as: :destroy_user
      patch "users/:id", to: "users#update", as: :patch_user
      put "users/:id", to: "users#update", as: :put_user
      resources :users, except: %i(destroy update)
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers
  belongs_to :category
  has_many :results, dependent: :destroy
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: %i(show update edit)

  def show; end

  def index
    @questions = Question.all.page(params[:page]).per Settings.number_page
  end

  def new
    @question = Question.new
    (Settings.number_answer).times {@question.answers.build}
  end
    
  def edit; end

  def create
    @question = Question.new params_question
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def update
    if @question.update(params[:question])
      redirect_to @question
    else
      render :edit
    end
  end

  private
  def params_question
    params.require(:question).permit :word, :category_id,
      answers_attributes: [:id, :mean, :correct]
  end

  def load_question
    @question = Question.find_by id: params[:id]
  end
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <div class="form-qa center">
    <%= f.label :word %>
    <%= f.text_field :word, class: "form-control" %>
    <%= f.collection_select :category_id, Category.all, :id,
    :name, include_blank: true %>
    <%= f.fields_for :answers do |ff| %>
      <div class="input-group">
        <span class="input-group-addon form-qa">
          <%= ff.check_box :correct%>
        </span>
        <%= ff.text_field :mean, class: "form-control" %>
      </div>
    <% end %>
    <br>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/questions/index.html.erb
<div class="container">
  <% @questions.each do |question|  %>
    <table class="table listwords center">
      <tr class="fix-table">
        <td> 
          <%= question.word %>
        </td>
        <td>
          <% question.answers.each do |answer| %>
            <%= answer.mean if answer.correct? %>
          <% end %>
        </td>
      </tr>
    </table>
    <br><br>
  <% end %>
  <%= paginate @questions %>
</div>

app/views/questions/new.html.erb
<div class="container">
  <%= render "form" %>
</div>

app/views/questions/show.html.erb
<%= @question.word %>
<%= link_to  "Create Question", createquestion_path %>