config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/createquestion", to: "questions#new"
    post "/createquestion", to: "questions#create"
    get "/createcategory", to: "categories#new"
    post "/createcategory", to: "categories#create"
    get "/createlesson", to: "lessons#new"
    post "/createlesson", to: "lessons#create"
    get "/testlesson", to: "results#new"
    post "/testlesson", to: "results#create"
    
    resources :users, only: %i(show edit update)
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :questions
    resources :categories
    resources :lessons
    resources :results

    namespace :admin do
      root "users#index"
      delete "/users/:id", to: "users#destroy",
        as: :destroy_user
      patch "users/:id", to: "users#update", as: :patch_user
      put "users/:id", to: "users#update", as: :put_user
      resources :users, except: %i(destroy update)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  VALID_EMAIL_REGEX = Settings.user_valid.email_syntax
  mount_uploader :avatar, AvatarUploader

  has_secure_password
  validates :name,  presence: true,
    length: {maximum: Settings.user_valid.name_length}
  validates :email, presence: true,
    length: {maximum: Settings.user_valid.email_length},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true,
    length: {minimum: Settings.user_valid.password_length}, allow_nil: true
  validate :avatar_size

  scope :selected, ->{select :id, :name, :email}
  scope :ordered, ->{order name: :asc}

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute :remember_digest, User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end

  def forget
    update_attribute :remember_digest, nil
  end

  def activate
    update_attributes activated: true, activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attributes reset_digest: User.digest(reset_token),
      reset_sent_at: Time.zone.now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_available?
    reset_sent_at > Settings.alive_time.reset_password.hours.ago
  end

  private

  def downcase_email
    email.downcase!
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest activation_token
  end

  def avatar_size
    if avatar.size > Settings.user_valid.avatar_size.megabytes
      errors.add :avatar, t(".image_alert")
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    before_action :logged_in_user, :admin_user,
      only: %i(load_user index)
    before_action :load_user, except: %i(index)
    before_action :correct_user, only: %i(edit update)

    def index
      @users = User.selected.ordered
        .page(params[:page]).per Settings.users.records
    end

    def edit; end

    def update
      if @user.update_attributes user_params
        flash[:success] = t ".profile_updated"
        redirect_to admin_user_url(@user)
      else
        render admin: :edit
      end
    end

    def show; end

    def destroy
      if @user.destroy
        flash[:success] = t ".success_delete", user_name: @user.name
        redirect_to admin_root_url
      else
        flash[:danger] = t ".error_delete"
      end
    end

    private

    def load_user
      return if @user = User.find_by(id: params[:id])
      flash[:danger] = t ".not_found"
      redirect_to admin_root_url
    end

    def user_params
      params.require(:user).permit :name, :email, :password,
        :password_confirmation, :avatar
    end

    def logged_in_user
      return if logged_in?
      store_location
      flash[:danger] = t ".require_login"
      redirect_to login_url
    end

    def correct_user
      return if current_user? User.find_by(id: params[:id])
      flash[:danger] = t ".error_permission"
      redirect_to admin_root_url
    end

    def admin_user
      return if current_user.admin?
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, :load_user, only: %i(show edit update)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: :destroy

  def new
    @user = User.new
  end

  def index
    @users = User.selected.ordered
      .page(params[:page]).per Settings.users.records
  end

  def create
    @user = User.new user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = t ".active_message"
      redirect_to root_url
    else
      flash[:danger] = t ".not_success"
      render :new
    end
  end

  def edit; end

  def update
    if @user.update_attributes user_params
      flash[:success] = t ".profile_updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def show; end

  private

  def load_user
    return if @user = User.find_by(id: params[:id])
    flash[:danger] = t ".not_found"
    redirect_to users_path
  end

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :avatar
  end

  def logged_in_user
    return if logged_in?
    store_location
    flash[:danger] = t ".require_login"
    redirect_to login_url
  end

  def correct_user
    return if current_user? User.find_by(id: params[:id])
    flash[:danger] = t ".error_permission"
    redirect_to root_url
  end

  def admin_user
    return if current_user.admin?
    redirect_to root_url
  end
end

app/views/users/_avatar.html.erb
<div>
  <%= image_tag @user.avatar.url %>
</div>
<br><br>
<div>
  <label for="avatar_upload">
    <%= t ".change_ava" %>
  </label>
  <%= f.file_field :avatar, id: "avatar_upload" %>
</div>
<%= javascript_include_tag "custom", "data-turbolinks-track": "reload" %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages" %>
  <%= f.label :name, t(".name") %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :email, t(".email") %>
  <%= f.email_field :email, class: "form-control" %>
  <%= f.label :password, t(".password") %>
  <%= f.password_field :password, class: "form-control" %>
  <%= f.label :password_confirmation, t(".password_confirmation") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  <%= f.submit yield(:submit_title), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<div class="col-md-3">
  <%= image_tag user.avatar.url if user.avatar? %>
</div>
<div class="col-md-9">
  <%= user.name %><br>
  <%= user.email %>
</div>

<% if current_user&.admin? && !current_user?(user) %>
  | <%= link_to t(".delete"), user, method: :delete,
    data: {confirm: t(".confirm")} %>
<% end %>

app/views/users/edit.html.erb
<% provide :title, t("page_title") %>
<% provide :submit_title, t(".submit_button") %>
<h1><%= t ".update_profile" %></h1>
 <div class="row">
    <%= form_for @user do |f| %>
      <div class="col-md-3">
        <%= render "avatar", f: f %>
      </div>
      <div class="col-md-6">
        <%= render "form", user: @user %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t ".page_title" %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= render user %>
    </li>
  <% end %>
  <%= paginate @users %>
</ul>
<br>

app/views/users/new.html.erb
<% provide :submit_title, t(".submit") %>
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <br><br><br>
    <h2 id="welcome1"><%= t ".welcome" %></h2>
    <h2 id="welcome2"><%= t ".e_learning" %></h2>
  </div>
  <div class="col-md-4">
    <h1><%= t ".sign_up" %></h1>
    <%= form_for @user do |f| %>
      <%= render "form" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="col-md-3">
  <%= image_tag @user.avatar.url %>
</div>
<div class="col-md-9">
  <%= @user.name %><br>
  <%= @user.email %><br>
  <%= link_to t(".edit_page"), edit_user_path(current_user) %><br>
  <%= link_to t(".logout_page"), logout_path, method: :delete %>
</div>