config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/createquestion", to: "questions#new"
    post "/createquestion", to: "questions#create"
    get "/createcategory", to: "categories#new"
    post "/createcategory", to: "categories#create"
    get "/createlesson", to: "lessons#new"
    post "/createlesson", to: "lessons#create"
    get "/testlesson", to: "results#new"
    post "/testlesson", to: "results#create"
    
    resources :users, only: %i(show edit update)
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :questions
    resources :categories
    resources :lessons
    resources :results

    namespace :admin do
      root "users#index"
      delete "/users/:id", to: "users#destroy",
        as: :destroy_user
      patch "users/:id", to: "users#update", as: :patch_user
      put "users/:id", to: "users#update", as: :put_user
      resources :users, except: %i(destroy update)
    end
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" id="ihead">
  <div class="container">
    <%= link_to t(".e_learning"), root_path, id: "logo" %>
    <nav>
      <% if logged_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t(".category"), categories_path %></li>
          <li><%= link_to t(".lesson"), lessons_path %></li>
          <li><%= link_to t(".logout"), logout_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t(".log_in"), login_path %></li>
          <li><%= link_to t(".sign_up"), signup_path %></li>
        </ul>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elearning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim"%>
  </head>
  <body>
    <%= render "layouts/header"%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>